version: "3"
services:
    database:
        hostname: mongodb
        container_name: mongodb
        image: mongo:4.4
        ports:
          - 27017:27017
    api:
        build: .
        environment:
            DB_HOST: mongodb
        ports:
        - "4000:4000"