version: "3"
services:
  broker:
    hostname: redpanda1
    container_name: redpanda1
    image: redpandadata/redpanda:latest
    ports:
      - 9092:9092
      - 9644:9644
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false --kafka-addr "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092" --advertise-kafka-addr "PLAINTEXT://redpanda1:29092,OUTSIDE://redpanda1:9092"
  database:
    hostname: mongodb
    container_name: mongodb
    image: mongo:6.0.5
    ports:
      - 27017:27017
  api:
    build: .
    image: amidatech/saraswati-hedis-results-api
    container_name: saraswati-hedis-results-api
    # Set environment variables from this file
    env_file:
      - .env
    environment:
      DB_HOST: mongodb
      DB_NAME: hedisdb
      DB_PORT: 27017
      KAFKA_BROKERS: redpanda1:9092
      KAFKA_QUEUE: hedis-measures
    ports:
      - "4000:4000"
networks:
  default:
    external: false
    name: cp-all-in-one-community_default
